version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: VideoProcessing.API/Dockerfile
    container_name: video-api
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: VideoProcessing.Worker/Dockerfile
    container_name: video-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
