name: .NET 8 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: |
        dotnet restore VideoProcessing.API/
        dotnet restore VideoProcessing.Worker/
        
    - name: Build
      run: |
        dotnet build VideoProcessing.API/ --no-restore
        dotnet build VideoProcessing.Worker/ --no-restore
